# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-08 19:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_info', models.CharField(max_length=200)),
                ('order_success', models.CharField(default=0, max_length=10)),
            ],
        ),
    ]
